# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Edith Maulandi
email: e.maulandi@gmail.com
description: # this means to ignore newlines until "baseurl:"
  en: My purpose is to create impact and engage through information design. I am striving to find the best way to represent data to trigger understanding and action.
  fr: Mon but est de créer de l’impact et de l’engagement grâce à au design de l’information. Je cherche continuellement à trouver la meilleure manière de représenter les données pour déclencher la compréhension et l’action
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: edithmaulandi
github_username:  emaulandi
linkedin_username: edith-m-12329070
pinterest_username: edithpatey
instagram_username: edith.visualize
author: Edith Maulandi

collections:
  projects:
    output: true
  clientsprojects:
    output: true
  projectshighlight:
    output: true
  inspiration:
    output: true

menu:
 en:
  - about.md
  - facilitation-en.md
  - talks-en.md
  - feedbacks.md
  - inspiration-en.md
 fr:
  - apropos.md
  - facilitation.md
  - talks-fr.md
  - retours.md
  - inspiration-fr.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-twitter-plugin
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
